config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :articles do
  	resources :comments
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :nama, presence: true, 
	length: { minimum: 5 }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@Article)
	end
	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
		end
		private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "Finto",password: "12345",except: [:index, :show]

	def index
		@articles = Article.all
	end
	def show
		@article = Article.find(params[:id])
	end
	def new 
		@article = Article.new
	end
	def edit
		@article = Article.find(params[:id])
	end
	def create
		@article = Article.new(article_params)
		@article.save
		redirect_to @article

	end
	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		redirect_to @article
	end
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
		end 
	private
	def article_params
		params.require(:article).permit(:nama, :email, :no_telp, :alamat)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end
		def destroy
			@article = Article.find(params[:article_id])
			@comment = @article.comments.find(params[:id])
			@comment.destroy
			redirect_to article_path(@article)
		end
	end
	private
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h1>Edit artcle</h1>
<% if @article.errors.any? %>
<div id='error_explanation'>
  <h2>
    <%= pluralize(@article.errors.count, "error") %> prohibited this data from being saved :
  </h2>
  <ul>
    <% @article.erros.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_with(model: @article, local: true) do |form| %>
<P> 
<%= form.label :nama %><br>
<%= form.text_field :nama %>
</p> 
<P>
<%=form.label :email %><br>
<%= form.text_field :email %>
</p>
<P>
<%= form.label :no_telp %><br>
<%= form.text_field :no_telp %>
</p>
<P>
<%= form.label :alamat %><br>
<%= form.text_area :alamat %>
</p>
<%= form.submit %>
<% end %>
<%= link_to 'back', articles_path %>

app/views/articles/index.html.erb
<%= link_to 'new article', new_article_path %>

<table class="table table-dark">
	<thead>
		<tr>
		<th>nama</th>
		<th>E-mail</th>
		<th>No Telp</th>
		<th>Alamat</th>
		<th></th>
		</tr>
	</thead>
	<tbody>
		<% @articles.each do |article| %>
		<tr>
			<td><%= article.nama %></td>
			<td><%= article.email %></td>
			<td><%= article.no_telp %></td>
			<td><%= article.alamat %></td>
			<td><%= link_to 'show' , article_path(article) %></td>
			<td><%= link_to 'edit', edit_article_path(article) %></td>
			<td><%= link_to 'destory', article_path(article), method: :delete, data: { confirm: 'are you sure ?' } %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
<% if @article.errors.any? %>
<div id='error_explanation'>
  <h2>
    <%= pluralize(@article.errors.count, "error") %> prohibited this data from being saved :
  </h2>
  <ul>
    <% @article.erros.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
  <p>
    <%= form.label :nama %><br>
    <%= form.text_field :nama %>
  </p>
 
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
 
  <p>
    <%= form.label :no_telp %><br>
    <%= form.text_field :no_telp %>
  </p>
 
  <p>
    <%= form.label :alamat %><br>
    <%= form.text_area :alamat %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<p>
<strong>Nama : </strong>
<%= @article.nama %>
</p>
<p>
<strong>E-mail : </strong>
<%= @article.email %>
</p>
<P>
<strong>No Telp : </strong>
<%= @article.no_telp %>
</p>
<P>
<strong>Alamat : </strong>
<%= @article.alamat%>
</p>
<h2>comments</h2>
<%= render @article.comments %>
<h2>Add a comment:</h2>
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
<P>
	<%= form.label :commenter %><br>
	<%= form.text_field :commenter %>
</P>
<p>
	<%= form.label :body %><br>
	<%= form.text_area :body %>
</P>
<p>
	<%= form.submit %>
</p>
<% end %>

<%= link_to 'edit', edit_article_path(@article) %>
<%= link_to 'back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome index</h1>
<p>hallo</p>
<%= link_to 'my blog', controller: 'articles' %>